### ISSUE TITLE
Compilers not added?

### ISSUE THREAD

**Issue by vsoch** [archspec/archspec-go#14]
I noticed when we parse the microarchitectures.json in Go, we don't add compilers:

https://github.com/archspec/archspec-go/blob/f806bb25b479cd2165a8cadc70f7ca0af8b4c3c3/archspec/cpu/microarchitecture.go#L68-L75

But they are in the data here (example): https://github.com/archspec/archspec-json/blob/d844bb36b21dfb9ff5d04727edfc08f592fc06af/cpu/microarchitectures.json#L51

Was this just a case of just not needing it yet, or is it something we might add (since we have the data)?

**Comment by alalazo** [comment]
This project has been half-baked since ever, the idea is to have feature parity with the Python package. Any help is welcome :slightly_smiling_face:
